---
- name: Copy network configuration template based on sdn value
  template:
    src: >-
      {%- if net_type == 'linux-bridges' -%}
        roles/networking/templates/linux-bridges.j2
      {%- elif net_type == 'linux-bonds' -%}
        roles/networking/templates/linux-bonds.j2
      {%- elif net_type == 'ovs-bonds' -%}
        roles/networking/templates/ovs-bonds.j2
      {%- elif net_type == 'ovs-bridges' -%}
        roles/networking/templates/ovs-bridges.j2
      {%- endif -%}
    dest: /etc/network/interfaces
  when: sdn is defined and sdn in ['linux-bridges', 'ovs-bonds']
  tags:
    - networking

- name: Reload networking service
  service:
    name: networking
    state: restarted
  notify:
    - Restart network interfaces
  tags:
    - networking