---
- name: Install openvswitch-switch package
  when: sdn is defined and sdn !== false
  apt:
    name: openvswitch-switch
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - networking

- name: Copy network configuration template based on sdn value
  template:
    src: "{{ 'roles/networking/templates/bridges-only/linux-bridges.j2' if sdn == 'linux-bridges' else 'roles/networking/templates/bonds-bridges/ovs-bonds.j2' }}"
    dest: /etc/network/interfaces
  when: sdn is defined and sdn in ['linux-bridges', 'ovs-bonds']
  tags:
    - networking

- name: Reload networking service
  service:
    name: networking
    state: restarted
  notify:
    - Restart network interfaces
  tags:
    - networking