---
- name: Install openvswitch-switch package
  apt:
    name: openvswitch-switch
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - pmx-nodes

- name: Copy network configuration template
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
  tags:
    - pmx-nodes

- name: Reload networking service
  service:
    name: networking
    state: restarted
  notify:
    - Restart network interfaces
  tags:
    - pmx-nodes