---
- name: Base configuration for all hosts.
  hosts: all
  become: true
  roles:
    - networking
    - repositories
    - ssh

- name: Cluster configuration for PVE hosts.
  hosts: pve
  become: false
  roles:
   - cluster
