# roles/pmx-nodes/tasks/repos.yml

- name: Set PBS Enterprise Sources
  when: enterprise == true
  ansible.builtin.template:
    src: pbs-enterprise.sources.j2
    dest: /etc/apt/sources.list.d/pbs-enterprise.sources
  tags:
    - repositories
    - pbs

- name: Set Proxmox Sources
  when: enterprise == false
  ansible.builtin.template:
    src: pbs-no-sub.sources.j2
    dest: /etc/apt/sources.list.d/pbs-no-sub.sources
  tags:
    - repositories
    - pbs

- name: Set Debian Sources
  ansible.builtin.template:
    src: debian.sources.j2
    dest: /etc/apt/sources.list.d/debian.sources
  tags:
    - repositories
    - pbs

- name: Update APT Cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache for 1 hour
  tags:
    - repositories
    - pbs

