# roles/pmx-nodes/tasks/repos.yml

- name: Set PVE Enterprise Sources
  when: enterprise == true
  ansible.builtin.template:
    src: pve-enterprise.sources.j2
    
    dest: /etc/apt/sources.list.d/pve-enterprise.sources
  tags:
    - repositories
    - pve

- name: Set Proxmox Sources
  when: enterprise == false
  ansible.builtin.template:
    src: pve-no-sub.sources.j2
    
    dest: /etc/apt/sources.list.d/pve-no-sub.sources
  tags:
    - repositories
    - pve

- name: Set Ceph Sources
  ansible.builtin.template:
    src: ceph.sources.j2
    dest: /etc/apt/sources.list.d/ceph.sources
  tags:
    - repositories
    - pve

- name: Set Debian Sources
  ansible.builtin.template:
    src: debian.sources.j2
    
    dest: /etc/apt/sources.list.d/debian.sources
  tags:
    - repositories
    - pve

- name: Update APT Cache
  become: true
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600  # Cache for 1 hour
  tags:
    - repositories
    - pve
