---
# roles/pmx-nodes/handlers/main.yml

- name: Restart Services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  loop:
    - openvswitch-switch

- name: Restart network interfaces
  command: systemctl restart networking.service