---
- name: Check if API user already exists on the node
  ansible.builtin.command: "pveum user list | grep '^{{ api_user }}@pve'"
  delegate_to: "{{ inventory_hostname }}" # Runs on each host in the play
  register: user_check
  changed_when: false
  failed_when: false
  tags:
    - pve
    - cluster

- name: Create API user if it does not exist
  ansible.builtin.command: "pveum user add {{ api_user }}@pve --password '{{ api_password }}'"
  delegate_to: "{{ inventory_hostname }}" # Runs on each host in the play
  when: user_check.rc != 0
  tags:
    - pve
    - cluster

- name: Ensure API user has the necessary permissions
  community.proxmox.proxmox_access_acl:
    api_host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    api_user: "root@pam"
    api_password: "{{ root_password }}"
    path: "/"
    roleid: "Administrator"
    ugid: "{{ api_user }}@pve"
    type: user  # <-- This is the fix
    state: present
  delegate_to: localhost
  tags:
    - pve
    - cluster

- name: Create Proxmox cluster on the leader node
  when: inventory_hostname == 'cave'
  community.proxmox.proxmox_cluster:
    api_host: "{{ pve_cluster_leader_node }}"
    api_user: "{{ api_user }}@pve"
    api_password: "{{ api_password }}"
    cluster_name: "{{ pve_cluster_name | default('pve-cluster') }}"
    link0: "{{ bridges[0].ip }}"
    state: present
  run_once: true
  delegate_to: localhost
  tags:
    - pve
    - cluster

- name: Get cluster join information from the leader node
  community.proxmox.proxmox_cluster_join_info:
    api_host: "{{ pve_cluster_leader_node }}"
    api_user: "{{ api_user }}@pve"
    api_password: "{{ api_password }}"
  register: pve_cluster_join_info
  run_once: true
  delegate_to: localhost
  tags:
    - pve
    - cluster

- name: Add follower nodes to the cluster
  when: inventory_hostname != 'cave'
  community.proxmox.proxmox_cluster:
    api_host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    api_user: "root@pam"
    api_password: "{{ root_password }}"
    state: present
    join_info: "{{ pve_cluster_join_info.join_config }}"
  delegate_to: localhost
  tags:
    - pve
    - cluster