---
- name: Attempt to create API user (and ignore 'no such user' error)
  community.proxmox.proxmox_user:
    api_host: "{{ pve_cluster_leader_node }}"
    api_user: "root@pam"
    api_password: "{{ root_password }}"
    userid: "{{ api_user }}@pve"
    password: "{{ api_password }}"
    enable: true
    state: present
  run_once: true
  delegate_to: localhost
  ignore_errors: true  # <-- This is the fix
  tags:
    - pve
    - cluster

- name: Ensure API user has the necessary permissions
  community.proxmox.proxmox_access_acl:
    api_host: "{{ pve_cluster_leader_node }}"
    api_user: "root@pam"
    api_password: "{{ root_password }}" # Make sure this is defined in your vault
    path: "/"
    role: "Administrator"
    propagate: 1
    users:
      - "{{ api_user }}@pve"
    state: present
  delegate_to: localhost
  tags:
    - pve
    - cluster

- name: Create Proxmox cluster on the leader node
  when: inventory_hostname == pve_cluster_leader_node
  community.proxmox.proxmox_cluster:
    api_host: "{{ pve_cluster_leader_node }}"
    api_user: "{{ api_user }}@pve"
    api_password: "{{ api_password }}"
    cluster_name: "{{ pve_cluster_name | default('pve-cluster') }}"
    link0: "{{ bridges[0].ip }}"
    state: present
  delegate_to: localhost
  tags:
    - pve
    - cluster

- name: Get cluster join information from the leader node
  community.proxmox.proxmox_cluster_join_info:
    api_host: "{{ pve_cluster_leader_node }}"
    api_user: "{{ api_user }}@pve"
    api_password: "{{ api_password }}"
  register: pve_cluster_join_info
  run_once: true
  delegate_to: "{{ pve_cluster_leader_node }}"
  tags:
    - pve
    - cluster

- name: Add follower nodes to the cluster
  when: inventory_hostname != pve_cluster_leader_node
  community.proxmox.proxmox_cluster:
    api_host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
    api_user: "root@pam"
    api_password: "{{ root_password }}" # Use root to join the cluster
    state: present
    join_info: "{{ pve_cluster_join_info.cluster_join }}"
    master_ip: "{{ ansible.builtin_facts.ipv4_address }}"
    fingerprint: "{{ cluster_fingerprint }}"
    cluster_name: "{{ pve_cluster_name | default('pve-cluster') }}"
  delegate_to: localhost
  tags:
    - pve
    - cluster