node-name: cave.local
cluster_leader: yes

primary-vlan-ip: 10.0.0.192
primary-vlan-mask: /24
primary-vlan-gateway: 10.0.0.1

cluster-vlan-ip: 10.0.7.192
cluster-vlan-mask: /24
cluster-vlan-gateway: 10.0.7.1

ceph-vlan-ip: 10.0.8.192
ceph-vlan-mask: /24
ceph-vlan-gateway: 10.0.8.1

migration-vlan-ip: 192.168.4.192
migration-vlan-mask: /24
migration-vlan-gateway: 192.168.4.1