node_name: plant.local
cluster_leader: no
enterprise: false
net_type: ovs-bridges

bridges:
  - name: vmbr0
    interface: eno1
    ip: 10.0.0.194
    mask: "24"
    gateway: 10.0.0.1
  - name: vmbr1
    interface: eno2
    ip: 10.0.7.194
    mask: "24"
    gateway: 10.0.7.1
  - name: vmbr2
    interface: eno3
    ip: 10.0.8.194
    mask: "24"
    gateway: 10.0.8.1
  - name: vmbr3
    interface: eno4
    ip: 192.168.4.194
    mask: "24"
    gateway: 192.168.4.1